version: 2

builds:
  - main: ./cmd/agent
    binary: draupnir
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "draupnir-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

changelog:
  disable: true

release:
  prerelease: auto
